# CMake generated Testfile for 
# Source directory: /home/runner/work/gperftools/gperftools
# Build directory: /home/runner/work/gperftools/gperftools/_codeql_build_dir
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(low_level_alloc_unittest "low_level_alloc_unittest")
set_tests_properties(low_level_alloc_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;458;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(stacktrace_unittest "stacktrace_unittest")
set_tests_properties(stacktrace_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;483;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(check_address_test "check_address_test")
set_tests_properties(check_address_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;487;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_minimal_unittest "tcmalloc_minimal_unittest")
set_tests_properties(tcmalloc_minimal_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;526;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_minimal_large_unittest "tcmalloc_minimal_large_unittest")
set_tests_properties(tcmalloc_minimal_large_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;532;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_minimal_large_heap_fragmentation_unittest "tcmalloc_minimal_large_heap_fragmentation_unittest")
set_tests_properties(tcmalloc_minimal_large_heap_fragmentation_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;538;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(addressmap_unittest "addressmap_unittest")
set_tests_properties(addressmap_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;543;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(system_alloc_unittest "system_alloc_unittest")
set_tests_properties(system_alloc_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;547;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(unique_path_unittest "unique_path_unittest")
set_tests_properties(unique_path_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;552;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(packed_cache_test "packed_cache_test")
set_tests_properties(packed_cache_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;558;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(frag_unittest "frag_unittest")
set_tests_properties(frag_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;562;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(markidle_unittest "markidle_unittest")
set_tests_properties(markidle_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;568;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(current_allocated_bytes_test "current_allocated_bytes_test")
set_tests_properties(current_allocated_bytes_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;573;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(malloc_hook_test "malloc_hook_test")
set_tests_properties(malloc_hook_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;581;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(malloc_extension_test "malloc_extension_test")
set_tests_properties(malloc_extension_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;585;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(malloc_extension_c_test "malloc_extension_c_test")
set_tests_properties(malloc_extension_c_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;589;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(memalign_unittest "memalign_unittest")
set_tests_properties(memalign_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;594;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(page_heap_test "page_heap_test")
set_tests_properties(page_heap_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;602;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(pagemap_unittest "pagemap_unittest")
set_tests_properties(pagemap_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;607;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(safe_strerror_test "safe_strerror_test")
set_tests_properties(safe_strerror_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;611;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(cleanup_test "cleanup_test")
set_tests_properties(cleanup_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;615;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(function_ref_test "function_ref_test")
set_tests_properties(function_ref_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;619;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(trivialre_test "trivialre_test")
set_tests_properties(trivialre_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;623;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(generic_writer_test "generic_writer_test")
set_tests_properties(generic_writer_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;627;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(proc_maps_iterator_test "proc_maps_iterator_test")
set_tests_properties(proc_maps_iterator_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;631;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(for_each_line_test "for_each_line_test")
set_tests_properties(for_each_line_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;635;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(realloc_unittest "realloc_unittest")
set_tests_properties(realloc_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;639;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(stack_trace_table_test "stack_trace_table_test")
set_tests_properties(stack_trace_table_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;647;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(thread_dealloc_unittest "thread_dealloc_unittest")
set_tests_properties(thread_dealloc_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;653;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(min_per_thread_cache_size_test "min_per_thread_cache_size_test")
set_tests_properties(min_per_thread_cache_size_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;657;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_minimal_debug_unittest "tcmalloc_minimal_debug_unittest")
set_tests_properties(tcmalloc_minimal_debug_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;697;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(malloc_extension_debug_test "malloc_extension_debug_test")
set_tests_properties(malloc_extension_debug_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;701;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(memalign_debug_unittest "memalign_debug_unittest")
set_tests_properties(memalign_debug_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;707;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(realloc_debug_unittest "realloc_debug_unittest")
set_tests_properties(realloc_debug_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;712;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(debugallocation_test "debugallocation_test")
set_tests_properties(debugallocation_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;717;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_unittest "tcmalloc_unittest")
set_tests_properties(tcmalloc_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;772;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_large_unittest "tcmalloc_large_unittest")
set_tests_properties(tcmalloc_large_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;776;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_large_heap_fragmentation_unittest "tcmalloc_large_heap_fragmentation_unittest")
set_tests_properties(tcmalloc_large_heap_fragmentation_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;780;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(heap_checker_stub_test "heap_checker_stub_test")
set_tests_properties(heap_checker_stub_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;784;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(sampler_test "sampler_test")
set_tests_properties(sampler_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;793;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(sampling_test "sampling_test")
set_tests_properties(sampling_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;800;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(heap-profiler_unittest.sh "/home/runner/work/gperftools/gperftools/src/tests/heap-profiler_unittest.sh" "/home/runner/work/gperftools/gperftools/_codeql_build_dir/heap-profiler_unittest")
set_tests_properties(heap-profiler_unittest.sh PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;805;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(tcmalloc_debug_unittest "tcmalloc_debug_unittest")
set_tests_properties(tcmalloc_debug_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;826;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(sampling_debug_test "sampling_debug_test")
set_tests_properties(sampling_debug_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;830;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(heap-profiler_debug_unittest.sh "/home/runner/work/gperftools/gperftools/src/tests/heap-profiler_unittest.sh" "/home/runner/work/gperftools/gperftools/_codeql_build_dir/heap-profiler_debug_unittest")
set_tests_properties(heap-profiler_debug_unittest.sh PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;835;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(getpc_test "getpc_test")
set_tests_properties(getpc_test PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;855;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(profiledata_unittest "profiledata_unittest")
set_tests_properties(profiledata_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;860;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(profile_handler_unittest "profile_handler_unittest")
set_tests_properties(profile_handler_unittest PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;865;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
add_test(profiler_unittest.sh "/home/runner/work/gperftools/gperftools/src/tests/profiler_unittest.sh")
set_tests_properties(profiler_unittest.sh PROPERTIES  ENVIRONMENT "BINDIR=.;TMPDIR=/tmp/perftools" _BACKTRACE_TRIPLES "/home/runner/work/gperftools/gperftools/CMakeLists.txt;867;add_test;/home/runner/work/gperftools/gperftools/CMakeLists.txt;0;")
